name:               "Jadsamia Medeiros"
description:        "Gosto de café"

url:                ""
#author:             "thinker3197"
email:              "jadsamiamedeiros11@gmail.com"
#gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
#twitter:            "jhondoe"
email:              "jadsamiamedeiros11@gmail.com"
github:             "jadsamiamedeiros"
#pinterest:          "jhondoe"
#linkedin:           "jhondoe"
facebook:           "jadsamia.medeiros"

disqus_shortname:   "thinker3197"

background:         "https://s3-sa-east-1.amazonaws.com/loja2/7dff0d08a23fa30ac2346cafb7c51469.png"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
 # - name:           "Download"
  #  href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "A"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
