{
	"version": 1512657059,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/by_alternativa-sheet0.png",
		"images/by_alternativa-sheet1.png",
		"images/by_alternativa-sheet2.png",
		"images/fundo-sheet0.png",
		"images/simbolos_res-sheet0.png",
		"images/fundo_vitoria-sheet0.png",
		"images/bt_voltar-sheet0.png",
		"images/fundo_derrota-sheet0.png",
		"images/bt_repetir-sheet0.png",
		"images/fundo_menu-sheet0.png",
		"images/bt_play-sheet0.png",
		"images/imagem_res-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/acertou.m4a",
		"media/acertou.ogg",
		"media/errou4.m4a",
		"media/errou4.ogg",
		"media/green screen botÃo inscreva-se. famosos com som (online-audio-converter.com).m4a",
		"media/green screen botÃo inscreva-se. famosos com som (online-audio-converter.com).ogg",
		"media/eg (online-audio-converter.com).m4a",
		"media/eg (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}