{
	"version": 1503343265,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundo-sheet0.png",
		"images/btinicial1-sheet0.png",
		"images/btescolha1-sheet0.png",
		"images/btescolha2-sheet0.png",
		"images/btopcao1-sheet0.png",
		"images/btplay-sheet0.png",
		"media/100% voce - chiclete com banana-[audiotrimmer.com] (1).m4a",
		"media/100% voce - chiclete com banana-[audiotrimmer.com] (1).ogg",
		"media/as meninas - xibom bombom-[audiotrimmer.com] (1).m4a",
		"media/as meninas - xibom bombom-[audiotrimmer.com] (1).ogg",
		"media/cheia de manias   raÇa negra-[audiotrimmer.com] (1).m4a",
		"media/cheia de manias   raÇa negra-[audiotrimmer.com] (1).ogg",
		"media/claudinho e buchecha - quero te encontrar-[audiotrimmer.com].m4a",
		"media/claudinho e buchecha - quero te encontrar-[audiotrimmer.com].ogg",
		"media/evidencias-[audiotrimmer.com].m4a",
		"media/evidencias-[audiotrimmer.com].ogg",
		"media/karaokê mulher de fases - raimundos-[audiotrimmer.com] (2).m4a",
		"media/karaokê mulher de fases - raimundos-[audiotrimmer.com] (2).ogg",
		"media/rouge - ragatanga-[audiotrimmer.com] (1).m4a",
		"media/rouge - ragatanga-[audiotrimmer.com] (1).ogg",
		"media/sandy e júnior - a lenda (karaokê)-[audiotrimmer.com].m4a",
		"media/sandy e júnior - a lenda (karaokê)-[audiotrimmer.com].ogg",
		"media/devagar katyperry-teenagedream[lyricsonscreen].m4a",
		"media/devagar katyperry-teenagedream[lyricsonscreen].ogg",
		"media/devagar onedirection-dragmedown.m4a",
		"media/devagar onedirection-dragmedown.ogg",
		"media/ed sheeran - photograph (official music video)-[audiotrimmer.com] (1).m4a",
		"media/ed sheeran - photograph (official music video)-[audiotrimmer.com] (1).ogg",
		"media/eminem - love the way you lie ft. rihanna-[audiotrimmer.com].m4a",
		"media/eminem - love the way you lie ft. rihanna-[audiotrimmer.com].ogg",
		"media/playback kt tunstall - suddenly i see.m4a",
		"media/playback kt tunstall - suddenly i see.ogg",
		"media/playback rachel platten - fight song.m4a",
		"media/playback rachel platten - fight song.ogg",
		"media/rapida rihannakanyewestpaulmccartney-fourfiveseconds.m4a",
		"media/rapida rihannakanyewestpaulmccartney-fourfiveseconds.ogg",
		"media/rapida theblackeyedpeas-myhumps.m4a",
		"media/rapida theblackeyedpeas-myhumps.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}