{
	"version": 1504551250,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/fundogenero-sheet0.png",
		"images/btinicial1-sheet0.png",
		"images/btescolha1-sheet0.png",
		"images/btescolha1-sheet1.png",
		"images/btescolha2-sheet0.png",
		"images/btescolha2-sheet1.png",
		"images/btopcao1-sheet0.png",
		"images/btplay-sheet0.png",
		"images/btplay-sheet1.png",
		"images/tiposgeneros-sheet0.png",
		"images/tiposgeneros-sheet1.png",
		"images/tiposgeneros-sheet2.png",
		"images/fundoalternativa-sheet0.png",
		"images/btrepaticao-sheet0.png",
		"images/btrepaticao-sheet1.png",
		"images/fundoopções-sheet0.png",
		"images/sprite-sheet0.png",
		"images/fundomenu-sheet0.png",
		"images/barratempo-sheet0.png",
		"images/botãosom-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite9-sheet0.png",
		"media/as meninas - xibom bombom-[audiotrimmer.com] (1).m4a",
		"media/as meninas - xibom bombom-[audiotrimmer.com] (1).ogg",
		"media/cheia de manias   raÇa negra-[audiotrimmer.com] (1).m4a",
		"media/cheia de manias   raÇa negra-[audiotrimmer.com] (1).ogg",
		"media/karaokê mulher de fases - raimundos-[audiotrimmer.com] (2).m4a",
		"media/karaokê mulher de fases - raimundos-[audiotrimmer.com] (2).ogg",
		"media/sandy e júnior - a lenda (karaokê)-[audiotrimmer.com].m4a",
		"media/sandy e júnior - a lenda (karaokê)-[audiotrimmer.com].ogg",
		"media/devagar katyperry-teenagedream[lyricsonscreen].m4a",
		"media/devagar katyperry-teenagedream[lyricsonscreen].ogg",
		"media/devagar onedirection-dragmedown.m4a",
		"media/devagar onedirection-dragmedown.ogg",
		"media/ed sheeran - photograph (official music video)-[audiotrimmer.com] (1).m4a",
		"media/ed sheeran - photograph (official music video)-[audiotrimmer.com] (1).ogg",
		"media/eminem - love the way you lie ft. rihanna-[audiotrimmer.com].m4a",
		"media/eminem - love the way you lie ft. rihanna-[audiotrimmer.com].ogg",
		"media/playback kt tunstall - suddenly i see.m4a",
		"media/playback kt tunstall - suddenly i see.ogg",
		"media/playback rachel platten - fight song.m4a",
		"media/playback rachel platten - fight song.ogg",
		"media/rapida rihannakanyewestpaulmccartney-fourfiveseconds.m4a",
		"media/rapida rihannakanyewestpaulmccartney-fourfiveseconds.ogg",
		"media/rapida theblackeyedpeas-myhumps.m4a",
		"media/rapida theblackeyedpeas-myhumps.ogg",
		"media/normal pabllo vittar - k.o. (videoclipe oficial).m4a",
		"media/normal pabllo vittar - k.o. (videoclipe oficial).ogg",
		"media/normal simone  simaria - loka ft. anitta.m4a",
		"media/normal simone  simaria - loka ft. anitta.ogg",
		"media/playback bruno mars - thats what i like-[audiotrimmer.com].m4a",
		"media/playback bruno mars - thats what i like-[audiotrimmer.com].ogg",
		"media/playback ed sheeran - shape of you.m4a",
		"media/playback ed sheeran - shape of you.ogg",
		"media/rapida katyperry-bonappétit(audio)ft.migos-.m4a",
		"media/rapida katyperry-bonappétit(audio)ft.migos-.ogg",
		"media/rapida majorlazer-suacara(feat.anittapabllovittar).m4a",
		"media/rapida majorlazer-suacara(feat.anittapabllovittar).ogg",
		"media/luisfonsi-despacitoft.daddyyankee(lyricslyricvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/luisfonsi-despacitoft.daddyyankee(lyricslyricvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/cazuza exagerado karaoke-[audiotrimmer.com].m4a",
		"media/cazuza exagerado karaoke-[audiotrimmer.com].ogg",
		"media/eurythmics - sweet dreams (are made of this) (official video)-[audiotrimmer.com].m4a",
		"media/eurythmics - sweet dreams (are made of this) (official video)-[audiotrimmer.com].ogg",
		"media/girlsjustwanttohave-- (online-audio-converter.com).m4a",
		"media/girlsjustwanttohave-- (online-audio-converter.com).ogg",
		"media/legiãourbana-tempoperdido(videoclipeofficial)-[audiotrimmer.com]-[audiotrimmer.com] (1).m4a",
		"media/legiãourbana-tempoperdido(videoclipeofficial)-[audiotrimmer.com]-[audiotrimmer.com] (1).ogg",
		"media/madonna-laislabonita(officialvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/madonna-laislabonita(officialvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/michaeljackson-billiejean(officialvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/michaeljackson-billiejean(officialvideo)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/18 take on me- (online-audio-converter.com).m4a",
		"media/18 take on me- (online-audio-converter.com).ogg",
		"media/sweet child o mine - full instrumental cover hd (online-audio-converter.com).m4a",
		"media/sweet child o mine - full instrumental cover hd (online-audio-converter.com).ogg",
		"media/chicletecombanana-100você-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/chicletecombanana-100você-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/evidências-chitãozinhoxororó-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/evidências-chitãozinhoxororó-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/ludmilla-cheguei(Áudiooficial)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/ludmilla-cheguei(Áudiooficial)-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/ragatanga-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/ragatanga-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/claudinhoebuchecha-queroteencontrar-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].m4a",
		"media/claudinhoebuchecha-queroteencontrar-[audiotrimmer.com]-[audiotrimmer.com]-[audiotrimmer.com].ogg",
		"media/reg (online-audio-converter.com).m4a",
		"media/reg (online-audio-converter.com).ogg",
		"media/167326_willy-ineedthatapp-com_click (online-audio-converter.com).m4a",
		"media/167326_willy-ineedthatapp-com_click (online-audio-converter.com).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}